### ISSUE TITLE
Complexity of finding the best arm 

### ISSUE THREAD

**Issue by govinda-kamath** [jkomiyama/banditlib#2]
Thank you for this excellent implementation of UCB.

While going through your code we found that you store each estimates of all arms as in a vector. Then for selecting the next arm you call `selectNextArm()` which finds the best arm by computing the maximum element in this vector using the `vectorMaxIndex ()` function in [utils](https://github.com/jkomiyama/banditlib/blob/b48b91de37cb7dfaf6d201b85e9b3a10f009e9b9/bandit/util.hpp).
```
template<class T>
int vectorMaxIndex(const std::vector<T> &elems){
  int m=0;
  T mv=elems[0];
  for(uint i=0;i<elems.size();++i){
    if(elems[i]>mv){
      mv=elems[i];
      m=i;
    }
  }
  return m;
}
```

This function seems to be linear in the number of arms. We (I and @bagavi) were thinking of implementing a UCB for a very large number of arms and were thinking of storing all arms as a priority queue so that this function can be achieved in logarithmic time (in the number of arms). We were wondering if we missed something there.

**Comment by jkomiyama** [comment]
Right, you can find the best arm in O(1) time if you adopt a data structure that has O(1) access to the maximum element. In that case, you need to keep the UCB score of each arm (that requires O(K) memory) and update the UCB score of the selected arm at the end of each round. 

Thompson sampling needs to draw posterior of each arm and requires O(K) time at each round.
